spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  INFO
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  ERROR