spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

user.filepath: /home/ubuntu/Projects/litemall/storage/

server:
  port: 8083

logging:
  level:
    root:  INFO
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  ERROR